# Generated by Django 3.1.5 on 2021-02-11 10:45

from django.db import migrations, models
import django.db.models.deletion
import news_profit.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_profit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news_profit.models.upload_to),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news_profit.models.upload_to)),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_profit.news')),
            ],
        ),
    ]
