# Generated by Django 3.1.5 on 2021-02-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_profit', '0002_auto_20210211_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
