# Generated by Django 3.1.5 on 2021-02-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_profit', '0003_auto_20210211_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='news_profit.news'),
        ),
    ]
